SET(TPIE_ROOTS
	${TPIE_ROOT}
	/usr
	/usr/local
	/opt/local
	/opt/csw
	/opt
	/sw
	c:/shared/gdal
	c:/devel/gdal
)

FIND_PATH(TPIE_INCLUDE_DIR	tpie.h
	HINTS
		$ENV{TPIE_ROOT}
	PATH_SUFFIXES
		include
		include/tpie
		include/TPIE
		tpie/
		TPIE/
	PATHS 
		${TPIE_ROOTS}
)


SET(TPIE_ROOTS ${TPIE_INCLUDE_DIR}/../ ${TPIE_INCLUDE_DIR}/../../ ${TPIE_ROOTS})

FIND_LIBRARY(TPIE_LIBRARY
	NAMES 
		tpie
	HINTS
		$ENV{TPIE_ROOT}
	PATH_SUFFIXES
		lib
	PATHS
		${TPIE_ROOTS}
)

FIND_LIBRARY(TPIE_LIBRARY_DEBUG
	NAMES 
		tpied	
	HINTS
		$ENV{TPIE_ROOT}
	PATH_SUFFIXES
		lib
	PATHS
		${TPIE_ROOTS}
)

GET_FILENAME_COMPONENT(TPIE_LIBRARY_DIR ${TPIE_LIBRARY} PATH) 

FIND_PATH(TPIE_CONFIG_H_DIR	tpie/config.h
	HINTS
		$ENV{TPIE_ROOT}
	PATH_SUFFIXES
		include
		include/tpie
		include/TPIE
		tpie/
		TPIE/
	PATHS 
		${TPIE_ROOTS}
		${TPIE_LIBRARY_DIR}/..
)


IF(TPIE_LIBRARY AND TPIE_LIBRARY_DEBUG)
	SET(TPIE_LIBRARY optimized ${TPIE_LIBRARY} debug ${TPIE_LIBRARY_DEBUG})
ENDIF(TPIE_LIBRARY AND TPIE_LIBRARY_DEBUG)

SET(TPIE_FOUND "NO")
IF(TPIE_LIBRARY AND TPIE_INCLUDE_DIR)
  SET(TPIE_FOUND "YES")
ENDIF(TPIE_LIBRARY AND TPIE_INCLUDE_DIR)

